### Build and install packages
FROM python:3.6
RUN \
  apt-get -y update && \
  apt-get install -y build-essential libpng-dev libjpeg-dev

# Install Python dependencies
ADD . /src
COPY builder/entrypoint-linux.sh /entrypoint.sh

WORKDIR /src/
RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir -r requirements.txt \
    && chmod +x /entrypoint.sh

VOLUME /src/

ENTRYPOINT ["/entrypoint.sh"]